[package]
name = "logistic_regression_model"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
ndarray = "0.15"
smartcore = "0.3"

[dev-dependencies]
# Add dev-dependencies if needed for testing
